// SPDX-License-Identifier: GPL-3.0-only
//! 语言数据表：月份名、星期名、日词、时段词、城市名与模板。
//! 所有条目均按各语言日常书写习惯手工编写；月份用该语言日期所需
//! 的格（如俄语、波兰语用属格），俄语/波兰语星期用 “在星期X” 中的宾格。

/// 模板里的一个片段；渲染时任一片段不适配则整个模板不可用。
#[derive(Debug, Clone, Copy)]
pub(crate) enum Seg {
    /// 固定文本
    Lit(&'static str),
    /// 日期表达（月名句式 / 日词 / 星期名）
    Date,
    /// ISO 数字日期，仅完整日期（避免月日顺序歧义）
    DateIso,
    /// 24 小时制时刻
    Time24,
    /// 12 小时制时刻（0 点与 12 点不适用）
    Time12,
    /// 用连字符表示的时间区间
    RangeDash,
    /// 用 “从…到…” 词表示的时间区间
    RangeFT,
    /// “在<城市>” 短语
    CityIn,
    /// “<城市>时间” 短语
    CityTime,
    /// UTC/GMT 偏移
    Utc,
    /// 星期名（可含 “下一…”）
    Wd,
    /// 星期名（不带 “下一…”，next 时不适用）
    WdPlain,
}

/// 一门语言的全部静态数据。
pub(crate) struct Lang {
    pub code: &'static str,
    /// 月份名（取日期句式所需的格）
    pub months: [&'static str; 12],
    /// 星期名（周一到周日，取句中所需的格）
    pub weekdays: [&'static str; 7],
    /// “下一…星期” 句式，{} 为星期名
    pub next_pat: &'static str,
    pub today: &'static str,
    pub tomorrow: &'static str,
    pub after_tomorrow: &'static str,
    pub yesterday: &'static str,
    /// “{} 天后” / “{} 天前” 句式
    pub in_days_pat: &'static str,
    pub ago_days_pat: &'static str,
    /// 12 小时制时段词：按 24 小时制小时（含端点）取词；
    /// 0 点与 12 点不在任何区间内，故 12 小时制模板对它们不可用。
    pub periods: &'static [(u8, u8, &'static str)],
    /// 24 小时制句式（{} 为 时:分），如德语 “{} Uhr”
    pub t24_pat: &'static str,
    /// 12 小时制句式：{h} 时、{m} 分、{p} 时段词
    pub t12_pat: &'static str,
    /// 完整日期句式：{Y} 年、{N} 月名、{n} 月数、{d} 日数
    pub date_abs_pat: &'static str,
    /// 月日句式
    pub date_md_pat: &'static str,
    /// “从 {a} 到 {b}” 句式
    pub from_to_pat: &'static str,
    /// 区间连字符
    pub dash: &'static str,
    /// “在{}” 城市句式
    pub city_in_pat: &'static str,
    /// “{}时间” 城市句式
    pub city_time_pat: &'static str,
    /// UTC/GMT 偏移句式（{} 为带符号的偏移）
    pub utc_pat: &'static str,
    /// 城市名，顺序与 CITY_KEYS 一致
    pub cities: [&'static str; 8],
    pub templates: &'static [&'static [Seg]],
}

/// 城市键（也是 `Zone::City` 允许的取值）。
pub(crate) const CITY_KEYS: [&str; 8] = [
    "tokyo",
    "london",
    "new york",
    "paris",
    "berlin",
    "sydney",
    "singapore",
    "los angeles",
];

pub const LANGUAGES: [&str; 16] = [
    "zh-Hans", "zh-Hant", "ja", "ko", "en", "de", "es", "fr", "it", "nl", "pl", "pt-BR", "ru",
    "tr", "vi", "id",
];

// 按代码查找语言。
pub(crate) fn lang(code: &str) -> Option<&'static Lang> {
    LANGS.iter().find(|l| l.code == code)
}

// —— 各语言模板（编号含义：0 裸时刻；1 裸 12 小时制；2 日期+时刻；
//    3 ISO 日期+时刻；4 时刻+城市；5 日期+时刻+城市；6 日期+区间；
//    7 从…到…区间；8 时刻+UTC；9 星期+时刻；10 星期(不带“下一”)+时刻；
//    11 日期+12 小时制；12 12 小时制+城市；13 日期+时刻+城市时间；
//    14 区间+UTC；15 日期+区间+城市）——

const T_ZH_HANS: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::Date, Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::Date, Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" "), Seg::Time24],
    &[Seg::Date, Seg::Time12],
    &[Seg::Time12, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::Date, Seg::Lit("，"), Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit("（"), Seg::RangeFT, Seg::Lit("，"), Seg::CityTime, Seg::Lit("）")],
];

const T_ZH_HANT: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::Date, Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::Date, Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" "), Seg::Time24],
    &[Seg::Date, Seg::Time12],
    &[Seg::Time12, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::Date, Seg::Lit("，"), Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit("（"), Seg::RangeFT, Seg::Lit("，"), Seg::CityTime, Seg::Lit("）")],
];

const T_JA: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit("の"), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit("、"), Seg::CityTime],
    &[Seg::Date, Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::Date, Seg::Lit(" "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit("の"), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit("の"), Seg::Time24],
    &[Seg::Date, Seg::Lit("の"), Seg::Time12],
    &[Seg::Time12, Seg::Lit("、"), Seg::CityTime],
    &[Seg::Date, Seg::Time24, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(" "), Seg::RangeFT, Seg::Lit("（"), Seg::CityTime, Seg::Lit("）")],
];

const T_KO: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(" "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" "), Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(" "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_EN: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" at "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" at "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" at "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" at "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" at "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_DE: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" um "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(", "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" um "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Lit("am "), Seg::Wd, Seg::Lit(" um "), Seg::Time24],
    &[Seg::Lit("am "), Seg::WdPlain, Seg::Lit(" um "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" um "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_ES: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" a las "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" a las "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Lit("el "), Seg::Wd, Seg::Lit(" a las "), Seg::Time24],
    &[Seg::Lit("el "), Seg::WdPlain, Seg::Lit(" a las "), Seg::Time24],
    &[Seg::Date, Seg::Lit(", "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_FR: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" à "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" à "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" à "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" à "), Seg::Time24],
    &[Seg::Date, Seg::Lit(", "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_IT: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" alle "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" alle "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" alle "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" alle "), Seg::Time24],
    &[Seg::Date, Seg::Lit(", "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_NL: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" om "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(", "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" om "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" om "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" om "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" om "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_PL: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" o "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(", "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" o "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Lit("w "), Seg::Wd, Seg::Lit(" o "), Seg::Time24],
    &[Seg::Lit("w "), Seg::WdPlain, Seg::Lit(" o "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" o "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_PT: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" às "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" às "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" às "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" às "), Seg::Time24],
    &[Seg::Date, Seg::Lit(", "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_RU: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" в "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(", "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" в "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Lit("в "), Seg::Wd, Seg::Lit(" в "), Seg::Time24],
    &[Seg::Lit("в "), Seg::WdPlain, Seg::Lit(" в "), Seg::Time24],
    &[Seg::Date, Seg::Lit(", "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_TR: [&[Seg]; 16] = [
    &[Seg::Lit("saat "), Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" saat "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(" saat "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" günü saat "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" günü saat "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" saat "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_VI: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" lúc "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" lúc "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" lúc "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" lúc "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" lúc "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(", "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(", "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

const T_ID: [&[Seg]; 16] = [
    &[Seg::Time24],
    &[Seg::Time12],
    &[Seg::Date, Seg::Lit(" pukul "), Seg::Time24],
    &[Seg::DateIso, Seg::Lit(" "), Seg::Time24],
    &[Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(" pukul "), Seg::Time24, Seg::Lit(" "), Seg::CityIn],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeDash],
    &[Seg::RangeFT],
    &[Seg::Time24, Seg::Lit(" "), Seg::Utc],
    &[Seg::Wd, Seg::Lit(" pukul "), Seg::Time24],
    &[Seg::WdPlain, Seg::Lit(" pukul "), Seg::Time24],
    &[Seg::Date, Seg::Lit(" pukul "), Seg::Time12],
    &[Seg::Time12, Seg::Lit(" "), Seg::CityTime],
    &[Seg::Date, Seg::Lit(", "), Seg::Time24, Seg::Lit(" "), Seg::CityTime],
    &[Seg::RangeFT, Seg::Lit(" "), Seg::Utc],
    &[Seg::Date, Seg::Lit(", "), Seg::RangeFT, Seg::Lit(" "), Seg::CityIn],
];

// 简体中文的月份（数字月）。
const M_NUM_ZH: [&str; 12] = [
    "1月", "2月", "3月", "4月", "5月", "6月", "7月", "8月", "9月", "10月", "11月", "12月",
];
// 越南语的月份（“第 n 月”）。
const M_VI: [&str; 12] = [
    "tháng 1", "tháng 2", "tháng 3", "tháng 4", "tháng 5", "tháng 6",
    "tháng 7", "tháng 8", "tháng 9", "tháng 10", "tháng 11", "tháng 12",
];
// 韩语的月份。
const M_KO: [&str; 12] = [
    "1월", "2월", "3월", "4월", "5월", "6월", "7월", "8월", "9월", "10월", "11월", "12월",
];

// 中文的时段词（简繁同形）：凌晨、早上、上午、下午、晚上。
const P_ZH: [(u8, u8, &str); 5] = [
    (1, 5, "凌晨"),
    (6, 8, "早上"),
    (9, 11, "上午"),
    (13, 17, "下午"),
    (18, 23, "晚上"),
];

pub(crate) static LANGS: [Lang; 16] = [
    // —— 简体中文 ——
    Lang {
        code: "zh-Hans",
        months: M_NUM_ZH,
        weekdays: ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"],
        next_pat: "下{}",
        today: "今天",
        tomorrow: "明天",
        after_tomorrow: "后天",
        yesterday: "昨天",
        in_days_pat: "{n}天后",
        ago_days_pat: "{n}天前",
        periods: &P_ZH,
        t24_pat: "{}",
        t12_pat: "{p}{h}:{m}",
        date_abs_pat: "{Y}年{N}{d}日",
        date_md_pat: "{N}{d}日",
        from_to_pat: "从{a}到{b}",
        dash: "\u{2013}",
        city_in_pat: "在{}",
        city_time_pat: "{}时间",
        utc_pat: "UTC{}",
        cities: ["东京", "伦敦", "纽约", "巴黎", "柏林", "悉尼", "新加坡", "洛杉矶"],
        templates: &T_ZH_HANS,
    },
    // —— 繁体中文 ——
    Lang {
        code: "zh-Hant",
        months: M_NUM_ZH,
        weekdays: ["星期一", "星期二", "星期三", "星期四", "星期五", "星期六", "星期日"],
        next_pat: "下{}",
        today: "今天",
        tomorrow: "明天",
        after_tomorrow: "後天",
        yesterday: "昨天",
        in_days_pat: "{n}天後",
        ago_days_pat: "{n}天前",
        periods: &P_ZH,
        t24_pat: "{}",
        t12_pat: "{p}{h}:{m}",
        date_abs_pat: "{Y}年{N}{d}日",
        date_md_pat: "{N}{d}日",
        from_to_pat: "從{a}到{b}",
        dash: "\u{2013}",
        city_in_pat: "在{}",
        city_time_pat: "{}時間",
        utc_pat: "UTC{}",
        cities: ["東京", "倫敦", "紐約", "巴黎", "柏林", "雪梨", "新加坡", "洛杉磯"],
        templates: &T_ZH_HANT,
    },
    // —— 日语 ——
    Lang {
        code: "ja",
        months: M_NUM_ZH,
        weekdays: ["月曜日", "火曜日", "水曜日", "木曜日", "金曜日", "土曜日", "日曜日"],
        next_pat: "次の{}",
        today: "今日",
        tomorrow: "明日",
        after_tomorrow: "明後日",
        yesterday: "昨日",
        in_days_pat: "{n}日後",
        ago_days_pat: "{n}日前",
        periods: &[(1, 11, "午前"), (13, 23, "午後")],
        t24_pat: "{}",
        t12_pat: "{p}{h}時{m}分",
        date_abs_pat: "{Y}年{N}{d}日",
        date_md_pat: "{N}{d}日",
        from_to_pat: "{a}から{b}まで",
        dash: "\u{2013}",
        city_in_pat: "{}で",
        city_time_pat: "{}時間",
        utc_pat: "UTC{}",
        cities: ["東京", "ロンドン", "ニューヨーク", "パリ", "ベルリン", "シドニー", "シンガポール", "ロサンゼルス"],
        templates: &T_JA,
    },
    // —— 韩语 ——
    Lang {
        code: "ko",
        months: M_KO,
        weekdays: ["월요일", "화요일", "수요일", "목요일", "금요일", "토요일", "일요일"],
        next_pat: "다음 {}",
        today: "오늘",
        tomorrow: "내일",
        after_tomorrow: "모레",
        yesterday: "어제",
        in_days_pat: "{n}일 후",
        ago_days_pat: "{n}일 전",
        periods: &[(1, 5, "새벽"), (6, 11, "오전"), (13, 23, "오후")],
        t24_pat: "{}",
        t12_pat: "{p} {h}시 {m}분",
        date_abs_pat: "{Y}년 {N} {d}일",
        date_md_pat: "{N} {d}일",
        from_to_pat: "{a}부터 {b}까지",
        dash: "\u{2013}",
        city_in_pat: "{} 기준",
        city_time_pat: "{} 시간",
        utc_pat: "UTC{}",
        cities: ["도쿄", "런던", "뉴욕", "파리", "베를린", "시드니", "싱가포르", "로스앤젤레스"],
        templates: &T_KO,
    },
    // —— 英语 ——
    Lang {
        code: "en",
        months: ["January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "November", "December"],
        weekdays: ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"],
        next_pat: "next {}",
        today: "today",
        tomorrow: "tomorrow",
        after_tomorrow: "the day after tomorrow",
        yesterday: "yesterday",
        in_days_pat: "in {n} days",
        ago_days_pat: "{n} days ago",
        periods: &[(1, 11, "AM"), (13, 23, "PM")],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{N} {d}, {Y}",
        date_md_pat: "{N} {d}",
        from_to_pat: "from {a} to {b}",
        dash: "\u{2013}",
        city_in_pat: "in {}",
        city_time_pat: "{} time",
        utc_pat: "UTC{}",
        cities: ["Tokyo", "London", "New York", "Paris", "Berlin", "Sydney", "Singapore", "Los Angeles"],
        templates: &T_EN,
    },
    // —— 德语 ——
    Lang {
        code: "de",
        months: ["Januar", "Februar", "März", "April", "Mai", "Juni", "Juli", "August", "September", "Oktober", "November", "Dezember"],
        weekdays: ["Montag", "Dienstag", "Mittwoch", "Donnerstag", "Freitag", "Samstag", "Sonntag"],
        next_pat: "nächsten {}",
        today: "heute",
        tomorrow: "morgen",
        after_tomorrow: "übermorgen",
        yesterday: "gestern",
        in_days_pat: "in {n} Tagen",
        ago_days_pat: "vor {n} Tagen",
        periods: &[
            (1, 4, "nachts"),
            (5, 9, "morgens"),
            (10, 11, "vormittags"),
            (13, 17, "nachmittags"),
            (18, 23, "abends"),
        ],
        t24_pat: "{} Uhr",
        t12_pat: "{h}:{m} Uhr {p}",
        date_abs_pat: "{d}. {N} {Y}",
        date_md_pat: "{d}. {N}",
        from_to_pat: "von {a} bis {b}",
        dash: "\u{2013}",
        city_in_pat: "in {}",
        city_time_pat: "{}-Zeit",
        utc_pat: "UTC{}",
        cities: ["Tokio", "London", "New York", "Paris", "Berlin", "Sydney", "Singapur", "Los Angeles"],
        templates: &T_DE,
    },
    // —— 西班牙语 ——
    Lang {
        code: "es",
        months: ["enero", "febrero", "marzo", "abril", "mayo", "junio", "julio", "agosto", "septiembre", "octubre", "noviembre", "diciembre"],
        weekdays: ["lunes", "martes", "miércoles", "jueves", "viernes", "sábado", "domingo"],
        next_pat: "próximo {}",
        today: "hoy",
        tomorrow: "mañana",
        after_tomorrow: "pasado mañana",
        yesterday: "ayer",
        in_days_pat: "en {n} días",
        ago_days_pat: "hace {n} días",
        periods: &[
            (1, 5, "de la madrugada"),
            (6, 11, "de la mañana"),
            (13, 19, "de la tarde"),
            (20, 23, "de la noche"),
        ],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} de {N} de {Y}",
        date_md_pat: "{d} de {N}",
        from_to_pat: "de {a} a {b}",
        dash: "\u{2013}",
        city_in_pat: "en {}",
        city_time_pat: "hora de {}",
        utc_pat: "GMT{}",
        cities: ["Tokio", "Londres", "Nueva York", "París", "Berlín", "Sídney", "Singapur", "Los Ángeles"],
        templates: &T_ES,
    },
    // —— 法语 ——
    Lang {
        code: "fr",
        months: ["janvier", "février", "mars", "avril", "mai", "juin", "juillet", "août", "septembre", "octobre", "novembre", "décembre"],
        weekdays: ["lundi", "mardi", "mercredi", "jeudi", "vendredi", "samedi", "dimanche"],
        next_pat: "{} prochain",
        today: "aujourd'hui",
        tomorrow: "demain",
        after_tomorrow: "après-demain",
        yesterday: "hier",
        in_days_pat: "dans {n} jours",
        ago_days_pat: "il y a {n} jours",
        periods: &[(1, 11, "du matin"), (13, 17, "de l'après-midi"), (18, 23, "du soir")],
        t24_pat: "{}",
        t12_pat: "{h} h {m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "de {a} à {b}",
        dash: "\u{2013}",
        city_in_pat: "à {}",
        city_time_pat: "heure de {}",
        utc_pat: "UTC{}",
        cities: ["Tokyo", "Londres", "New York", "Paris", "Berlin", "Sydney", "Singapour", "Los Angeles"],
        templates: &T_FR,
    },
    // —— 意大利语 ——
    Lang {
        code: "it",
        months: ["gennaio", "febbraio", "marzo", "aprile", "maggio", "giugno", "luglio", "agosto", "settembre", "ottobre", "novembre", "dicembre"],
        weekdays: ["lunedì", "martedì", "mercoledì", "giovedì", "venerdì", "sabato", "domenica"],
        next_pat: "{} prossimo",
        today: "oggi",
        tomorrow: "domani",
        after_tomorrow: "dopodomani",
        yesterday: "ieri",
        in_days_pat: "tra {n} giorni",
        ago_days_pat: "{n} giorni fa",
        periods: &[
            (1, 4, "di notte"),
            (5, 11, "del mattino"),
            (13, 17, "del pomeriggio"),
            (18, 23, "di sera"),
        ],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "dalle {a} alle {b}",
        dash: "\u{2013}",
        city_in_pat: "a {}",
        city_time_pat: "ora di {}",
        utc_pat: "UTC{}",
        cities: ["Tokyo", "Londra", "New York", "Parigi", "Berlino", "Sydney", "Singapore", "Los Angeles"],
        templates: &T_IT,
    },
    // —— 荷兰语 ——
    Lang {
        code: "nl",
        months: ["januari", "februari", "maart", "april", "mei", "juni", "juli", "augustus", "september", "oktober", "november", "december"],
        weekdays: ["maandag", "dinsdag", "woensdag", "donderdag", "vrijdag", "zaterdag", "zondag"],
        next_pat: "volgende {}",
        today: "vandaag",
        tomorrow: "morgen",
        after_tomorrow: "overmorgen",
        yesterday: "gisteren",
        in_days_pat: "over {n} dagen",
        ago_days_pat: "{n} dagen geleden",
        periods: &[
            (1, 5, "'s nachts"),
            (6, 11, "'s ochtends"),
            (13, 17, "'s middags"),
            (18, 23, "'s avonds"),
        ],
        t24_pat: "{} uur",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "van {a} tot {b}",
        dash: "\u{2013}",
        city_in_pat: "in {}",
        city_time_pat: "{}-tijd",
        utc_pat: "UTC{}",
        cities: ["Tokio", "Londen", "New York", "Parijs", "Berlijn", "Sydney", "Singapore", "Los Angeles"],
        templates: &T_NL,
    },
    // —— 波兰语（月份属格，星期为 “w 星期X” 的宾格）——
    Lang {
        code: "pl",
        months: ["stycznia", "lutego", "marca", "kwietnia", "maja", "czerwca", "lipca", "sierpnia", "września", "października", "listopada", "grudnia"],
        weekdays: ["poniedziałek", "wtorek", "środę", "czwartek", "piątek", "sobotę", "niedzielę"],
        next_pat: "{} w przyszłym tygodniu",
        today: "dzisiaj",
        tomorrow: "jutro",
        after_tomorrow: "pojutrze",
        yesterday: "wczoraj",
        in_days_pat: "za {n} dni",
        ago_days_pat: "{n} dni temu",
        periods: &[
            (1, 4, "w nocy"),
            (5, 10, "rano"),
            (11, 11, "przed południem"),
            (13, 17, "po południu"),
            (18, 23, "wieczorem"),
        ],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "od {a} do {b}",
        dash: "\u{2013}",
        city_in_pat: "w {}",
        city_time_pat: "czas w {}",
        utc_pat: "UTC{}",
        cities: ["Tokio", "Londynie", "Nowym Jorku", "Paryżu", "Berlinie", "Sydney", "Singapurze", "Los Angeles"],
        templates: &T_PL,
    },
    // —— 巴西葡萄牙语 ——
    Lang {
        code: "pt-BR",
        months: ["janeiro", "fevereiro", "março", "abril", "maio", "junho", "julho", "agosto", "setembro", "outubro", "novembro", "dezembro"],
        weekdays: ["segunda-feira", "terça-feira", "quarta-feira", "quinta-feira", "sexta-feira", "sábado", "domingo"],
        next_pat: "{} que vem",
        today: "hoje",
        tomorrow: "amanhã",
        after_tomorrow: "depois de amanhã",
        yesterday: "ontem",
        in_days_pat: "em {n} dias",
        ago_days_pat: "há {n} dias",
        periods: &[
            (1, 5, "da madrugada"),
            (6, 11, "da manhã"),
            (13, 18, "da tarde"),
            (19, 23, "da noite"),
        ],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} de {N} de {Y}",
        date_md_pat: "{d} de {N}",
        from_to_pat: "das {a} às {b}",
        dash: "\u{2013}",
        city_in_pat: "em {}",
        city_time_pat: "horário de {}",
        utc_pat: "GMT{}",
        cities: ["Tóquio", "Londres", "Nova York", "Paris", "Berlim", "Sydney", "Singapura", "Los Angeles"],
        templates: &T_PT,
    },
    // —— 俄语（月份属格，星期为 “в 星期X” 的宾格）——
    Lang {
        code: "ru",
        months: ["января", "февраля", "марта", "апреля", "мая", "июня", "июля", "августа", "сентября", "октября", "ноября", "декабря"],
        weekdays: ["понедельник", "вторник", "среду", "четверг", "пятницу", "субботу", "воскресенье"],
        next_pat: "{} на следующей неделе",
        today: "сегодня",
        tomorrow: "завтра",
        after_tomorrow: "послезавтра",
        yesterday: "вчера",
        in_days_pat: "через {n} дн.",
        ago_days_pat: "{n} дн. назад",
        periods: &[(1, 3, "ночи"), (4, 11, "утра"), (13, 16, "дня"), (17, 23, "вечера")],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "с {a} до {b}",
        dash: "\u{2013}",
        city_in_pat: "в {}",
        city_time_pat: "время в {}",
        utc_pat: "UTC{}",
        cities: ["Токио", "Лондоне", "Нью-Йорке", "Париже", "Берлине", "Сиднее", "Сингапуре", "Лос-Анджелесе"],
        templates: &T_RU,
    },
    // —— 土耳其语 ——
    Lang {
        code: "tr",
        months: ["Ocak", "Şubat", "Mart", "Nisan", "Mayıs", "Haziran", "Temmuz", "Ağustos", "Eylül", "Ekim", "Kasım", "Aralık"],
        weekdays: ["Pazartesi", "Salı", "Çarşamba", "Perşembe", "Cuma", "Cumartesi", "Pazar"],
        next_pat: "gelecek {}",
        today: "bugün",
        tomorrow: "yarın",
        after_tomorrow: "öbür gün",
        yesterday: "dün",
        in_days_pat: "{n} gün sonra",
        ago_days_pat: "{n} gün önce",
        periods: &[
            (1, 4, "gece"),
            (5, 11, "sabah"),
            (13, 17, "öğleden sonra"),
            (18, 23, "akşam"),
        ],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "{a} ile {b} arasında",
        dash: "\u{2013}",
        city_in_pat: "{} saatinde",
        city_time_pat: "{} saati",
        utc_pat: "UTC{}",
        cities: ["Tokyo", "Londra", "New York", "Paris", "Berlin", "Sidney", "Singapur", "Los Angeles"],
        templates: &T_TR,
    },
    // —— 越南语 ——
    Lang {
        code: "vi",
        months: M_VI,
        weekdays: ["thứ hai", "thứ ba", "thứ tư", "thứ năm", "thứ sáu", "thứ bảy", "chủ nhật"],
        next_pat: "{} tuần sau",
        today: "hôm nay",
        tomorrow: "ngày mai",
        after_tomorrow: "ngày mốt",
        yesterday: "hôm qua",
        in_days_pat: "{n} ngày nữa",
        ago_days_pat: "{n} ngày trước",
        periods: &[(1, 10, "sáng"), (11, 11, "trưa"), (13, 17, "chiều"), (18, 23, "tối")],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "từ {a} đến {b}",
        dash: "\u{2013}",
        city_in_pat: "ở {}",
        city_time_pat: "giờ {}",
        utc_pat: "GMT{}",
        cities: ["Tokyo", "Luân Đôn", "New York", "Paris", "Berlin", "Sydney", "Singapore", "Los Angeles"],
        templates: &T_VI,
    },
    // —— 印尼语 ——
    Lang {
        code: "id",
        months: ["Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember"],
        weekdays: ["Senin", "Selasa", "Rabu", "Kamis", "Jumat", "Sabtu", "Minggu"],
        next_pat: "{} depan",
        today: "hari ini",
        tomorrow: "besok",
        after_tomorrow: "besok lusa",
        yesterday: "kemarin",
        in_days_pat: "{n} hari lagi",
        ago_days_pat: "{n} hari lalu",
        periods: &[
            (1, 10, "pagi"),
            (11, 11, "siang"),
            (13, 14, "siang"),
            (15, 17, "sore"),
            (18, 23, "malam"),
        ],
        t24_pat: "{}",
        t12_pat: "{h}:{m} {p}",
        date_abs_pat: "{d} {N} {Y}",
        date_md_pat: "{d} {N}",
        from_to_pat: "dari {a} hingga {b}",
        dash: "\u{2013}",
        city_in_pat: "di {}",
        city_time_pat: "waktu {}",
        utc_pat: "UTC{}",
        cities: ["Tokyo", "London", "New York", "Paris", "Berlin", "Sydney", "Singapura", "Los Angeles"],
        templates: &T_ID,
    },
];
